package com.evilgeniustechnologies.dclocator.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_CONNECTION.
*/
public class EntityConnectionDao extends AbstractDao<EntityConnection, Long> {

    public static final String TABLENAME = "ENTITY_CONNECTION";

    /**
     * Properties of entity EntityConnection.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MemberId = new Property(1, String.class, "memberId", false, "MEMBER_ID");
        public final static Property GroupId = new Property(2, String.class, "groupId", false, "GROUP_ID");
    };

    private DaoSession daoSession;

    private Query<EntityConnection> member_GroupConnectionsQuery;
    private Query<EntityConnection> messageGroup_MemberConnectionsQuery;

    public EntityConnectionDao(DaoConfig config) {
        super(config);
    }
    
    public EntityConnectionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_CONNECTION' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'MEMBER_ID' TEXT," + // 1: memberId
                "'GROUP_ID' TEXT);"); // 2: groupId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_CONNECTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityConnection entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String memberId = entity.getMemberId();
        if (memberId != null) {
            stmt.bindString(2, memberId);
        }
 
        String groupId = entity.getGroupId();
        if (groupId != null) {
            stmt.bindString(3, groupId);
        }
    }

    @Override
    protected void attachEntity(EntityConnection entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public EntityConnection readEntity(Cursor cursor, int offset) {
        EntityConnection entity = new EntityConnection( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // memberId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // groupId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityConnection entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMemberId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGroupId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(EntityConnection entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(EntityConnection entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "groupConnections" to-many relationship of Member. */
    public List<EntityConnection> _queryMember_GroupConnections(String memberId) {
        synchronized (this) {
            if (member_GroupConnectionsQuery == null) {
                QueryBuilder<EntityConnection> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MemberId.eq(null));
                member_GroupConnectionsQuery = queryBuilder.build();
            }
        }
        Query<EntityConnection> query = member_GroupConnectionsQuery.forCurrentThread();
        query.setParameter(0, memberId);
        return query.list();
    }

    /** Internal query to resolve the "memberConnections" to-many relationship of MessageGroup. */
    public List<EntityConnection> _queryMessageGroup_MemberConnections(String groupId) {
        synchronized (this) {
            if (messageGroup_MemberConnectionsQuery == null) {
                QueryBuilder<EntityConnection> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GroupId.eq(null));
                messageGroup_MemberConnectionsQuery = queryBuilder.build();
            }
        }
        Query<EntityConnection> query = messageGroup_MemberConnectionsQuery.forCurrentThread();
        query.setParameter(0, groupId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMemberDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMessageGroupDao().getAllColumns());
            builder.append(" FROM ENTITY_CONNECTION T");
            builder.append(" LEFT JOIN MEMBER T0 ON T.'MEMBER_ID'=T0.'OBJECT_ID'");
            builder.append(" LEFT JOIN MESSAGE_GROUP T1 ON T.'GROUP_ID'=T1.'OBJECT_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected EntityConnection loadCurrentDeep(Cursor cursor, boolean lock) {
        EntityConnection entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Member member = loadCurrentOther(daoSession.getMemberDao(), cursor, offset);
        entity.setMember(member);
        offset += daoSession.getMemberDao().getAllColumns().length;

        MessageGroup group = loadCurrentOther(daoSession.getMessageGroupDao(), cursor, offset);
        entity.setGroup(group);

        return entity;    
    }

    public EntityConnection loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<EntityConnection> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<EntityConnection> list = new ArrayList<EntityConnection>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<EntityConnection> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<EntityConnection> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
