package com.evilgeniustechnologies.dclocator.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LIKED_CONNECTION.
*/
public class LikedConnectionDao extends AbstractDao<LikedConnection, Long> {

    public static final String TABLENAME = "LIKED_CONNECTION";

    /**
     * Properties of entity LikedConnection.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LikedMessageId = new Property(1, String.class, "likedMessageId", false, "LIKED_MESSAGE_ID");
        public final static Property LikedUserId = new Property(2, String.class, "likedUserId", false, "LIKED_USER_ID");
    };

    private DaoSession daoSession;

    private Query<LikedConnection> message_LikedByConnectionsQuery;
    private Query<LikedConnection> member_LikedByConnectionsQuery;

    public LikedConnectionDao(DaoConfig config) {
        super(config);
    }
    
    public LikedConnectionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LIKED_CONNECTION' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'LIKED_MESSAGE_ID' TEXT," + // 1: likedMessageId
                "'LIKED_USER_ID' TEXT);"); // 2: likedUserId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LIKED_CONNECTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LikedConnection entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String likedMessageId = entity.getLikedMessageId();
        if (likedMessageId != null) {
            stmt.bindString(2, likedMessageId);
        }
 
        String likedUserId = entity.getLikedUserId();
        if (likedUserId != null) {
            stmt.bindString(3, likedUserId);
        }
    }

    @Override
    protected void attachEntity(LikedConnection entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LikedConnection readEntity(Cursor cursor, int offset) {
        LikedConnection entity = new LikedConnection( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // likedMessageId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // likedUserId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LikedConnection entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLikedMessageId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLikedUserId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LikedConnection entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LikedConnection entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "likedByConnections" to-many relationship of Message. */
    public List<LikedConnection> _queryMessage_LikedByConnections(String likedMessageId) {
        synchronized (this) {
            if (message_LikedByConnectionsQuery == null) {
                QueryBuilder<LikedConnection> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LikedMessageId.eq(null));
                message_LikedByConnectionsQuery = queryBuilder.build();
            }
        }
        Query<LikedConnection> query = message_LikedByConnectionsQuery.forCurrentThread();
        query.setParameter(0, likedMessageId);
        return query.list();
    }

    /** Internal query to resolve the "likedByConnections" to-many relationship of Member. */
    public List<LikedConnection> _queryMember_LikedByConnections(String likedUserId) {
        synchronized (this) {
            if (member_LikedByConnectionsQuery == null) {
                QueryBuilder<LikedConnection> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LikedUserId.eq(null));
                member_LikedByConnectionsQuery = queryBuilder.build();
            }
        }
        Query<LikedConnection> query = member_LikedByConnectionsQuery.forCurrentThread();
        query.setParameter(0, likedUserId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMessageDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMemberDao().getAllColumns());
            builder.append(" FROM LIKED_CONNECTION T");
            builder.append(" LEFT JOIN MESSAGE T0 ON T.'LIKED_MESSAGE_ID'=T0.'OBJECT_ID'");
            builder.append(" LEFT JOIN MEMBER T1 ON T.'LIKED_USER_ID'=T1.'OBJECT_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LikedConnection loadCurrentDeep(Cursor cursor, boolean lock) {
        LikedConnection entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Message likedMessage = loadCurrentOther(daoSession.getMessageDao(), cursor, offset);
        entity.setLikedMessage(likedMessage);
        offset += daoSession.getMessageDao().getAllColumns().length;

        Member likedUser = loadCurrentOther(daoSession.getMemberDao(), cursor, offset);
        entity.setLikedUser(likedUser);

        return entity;    
    }

    public LikedConnection loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LikedConnection> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LikedConnection> list = new ArrayList<LikedConnection>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LikedConnection> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LikedConnection> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
