package com.evilgeniustechnologies.dclocator.daos;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table METADATA.
 */
public class Metadata {

    private Long id;
    private java.util.Date tempLocationDate;
    private java.util.Date latestLocationDate;
    private java.util.Date tempMemberDate;
    private java.util.Date latestMemberDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Metadata() {
    }

    public Metadata(Long id) {
        this.id = id;
    }

    public Metadata(Long id, java.util.Date tempLocationDate, java.util.Date latestLocationDate, java.util.Date tempMemberDate, java.util.Date latestMemberDate) {
        this.id = id;
        this.tempLocationDate = tempLocationDate;
        this.latestLocationDate = latestLocationDate;
        this.tempMemberDate = tempMemberDate;
        this.latestMemberDate = latestMemberDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getTempLocationDate() {
        return tempLocationDate;
    }

    public void setTempLocationDate(java.util.Date tempLocationDate) {
        this.tempLocationDate = tempLocationDate;
    }

    public java.util.Date getLatestLocationDate() {
        return latestLocationDate;
    }

    public void setLatestLocationDate(java.util.Date latestLocationDate) {
        this.latestLocationDate = latestLocationDate;
    }

    public java.util.Date getTempMemberDate() {
        return tempMemberDate;
    }

    public void setTempMemberDate(java.util.Date tempMemberDate) {
        this.tempMemberDate = tempMemberDate;
    }

    public java.util.Date getLatestMemberDate() {
        return latestMemberDate;
    }

    public void setLatestMemberDate(java.util.Date latestMemberDate) {
        this.latestMemberDate = latestMemberDate;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        return "Metadata{" + '\n' +
                "id=" + id + '\n' +
                ", tempLocationDate=" + tempLocationDate + '\n' +
                ", latestLocationDate=" + latestLocationDate + '\n' +
                ", tempMemberDate=" + tempMemberDate + '\n' +
                ", latestMemberDate=" + latestMemberDate + '\n' +
                '}';
    }
    // KEEP METHODS END

}
