package com.evilgeniustechnologies.dclocator.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table READ_CONNECTION.
*/
public class ReadConnectionDao extends AbstractDao<ReadConnection, Long> {

    public static final String TABLENAME = "READ_CONNECTION";

    /**
     * Properties of entity ReadConnection.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ReadMessageId = new Property(1, String.class, "readMessageId", false, "READ_MESSAGE_ID");
        public final static Property ReadUserId = new Property(2, String.class, "readUserId", false, "READ_USER_ID");
    };

    private DaoSession daoSession;

    private Query<ReadConnection> message_ReadByConnectionsQuery;
    private Query<ReadConnection> member_ReadByConnectionsQuery;

    public ReadConnectionDao(DaoConfig config) {
        super(config);
    }
    
    public ReadConnectionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'READ_CONNECTION' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'READ_MESSAGE_ID' TEXT," + // 1: readMessageId
                "'READ_USER_ID' TEXT);"); // 2: readUserId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'READ_CONNECTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ReadConnection entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String readMessageId = entity.getReadMessageId();
        if (readMessageId != null) {
            stmt.bindString(2, readMessageId);
        }
 
        String readUserId = entity.getReadUserId();
        if (readUserId != null) {
            stmt.bindString(3, readUserId);
        }
    }

    @Override
    protected void attachEntity(ReadConnection entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ReadConnection readEntity(Cursor cursor, int offset) {
        ReadConnection entity = new ReadConnection( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // readMessageId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // readUserId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ReadConnection entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReadMessageId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setReadUserId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ReadConnection entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ReadConnection entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "readByConnections" to-many relationship of Message. */
    public List<ReadConnection> _queryMessage_ReadByConnections(String readMessageId) {
        synchronized (this) {
            if (message_ReadByConnectionsQuery == null) {
                QueryBuilder<ReadConnection> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ReadMessageId.eq(null));
                message_ReadByConnectionsQuery = queryBuilder.build();
            }
        }
        Query<ReadConnection> query = message_ReadByConnectionsQuery.forCurrentThread();
        query.setParameter(0, readMessageId);
        return query.list();
    }

    /** Internal query to resolve the "readByConnections" to-many relationship of Member. */
    public List<ReadConnection> _queryMember_ReadByConnections(String readMessageId) {
        synchronized (this) {
            if (member_ReadByConnectionsQuery == null) {
                QueryBuilder<ReadConnection> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ReadMessageId.eq(null));
                member_ReadByConnectionsQuery = queryBuilder.build();
            }
        }
        Query<ReadConnection> query = member_ReadByConnectionsQuery.forCurrentThread();
        query.setParameter(0, readMessageId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMessageDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMemberDao().getAllColumns());
            builder.append(" FROM READ_CONNECTION T");
            builder.append(" LEFT JOIN MESSAGE T0 ON T.'READ_MESSAGE_ID'=T0.'OBJECT_ID'");
            builder.append(" LEFT JOIN MEMBER T1 ON T.'READ_USER_ID'=T1.'OBJECT_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ReadConnection loadCurrentDeep(Cursor cursor, boolean lock) {
        ReadConnection entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Message readMessage = loadCurrentOther(daoSession.getMessageDao(), cursor, offset);
        entity.setReadMessage(readMessage);
        offset += daoSession.getMessageDao().getAllColumns().length;

        Member readUser = loadCurrentOther(daoSession.getMemberDao(), cursor, offset);
        entity.setReadUser(readUser);

        return entity;    
    }

    public ReadConnection loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ReadConnection> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ReadConnection> list = new ArrayList<ReadConnection>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ReadConnection> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ReadConnection> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
